---

- name: Install process
  become: True
  vars:
    side: ""
    mysql_version: "8"
    def_dir: "../file"
    version: ""
    java_home: "/usr/java/default"
    find_path: "{{ def_dir }}"
    dest_path: "/home/{{ username }}"
    suser: ['root', 'attps']
    tmp_dir: "/tmp"
    msql_dir: "{{ clayhome }}/script"
    host: "presence{{ side }}"
    oversion: "2.6.2-nr"
    nversion: "2.6.3-nr"
    host: "presnece{{ side }}"
  hosts: "{{ host | lower }}"

  roles:
    - role: upgrade-presence
    - role: install-clay
