---

- name: update profile
  become: True
  lineinfile:
    path: /etc/profile
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^JAVA_HOME=', line: 'export JAVA_HOME=/usr/lib/jvm/java' }
    - { regexp: '^CATALINA_HOME=', line: 'CATALINA_HOME=/apps/tomcat' }
    - { regexp: '^PATH=', line: 'PATH=$PATH:$JAVA_HOME/bin:/bin:/sbin' }
    - { regexp: '^CLASSPATH=', line: 'CLASSPATH=$JAVA_HOME/jre/lib:$JAVA_HOME/lib/tools.jar:$CATALINA_HOME/lib-jsp-api.jar:$CATALINA_HOME/lib/servlet-api.jar' }
    - { regexp: '^export CUDA_VISIBLE_DEVICES=', line: 'export CUDA_VISIBLE_DEVICES=0' }
    - { regexp: '^export CUDA_MPS_PIPE_DIRECTORY=', line: 'export CUDA_MPS_PIPE_DIRECTORY=/tmp/nvidia-mps' }
    - { regexp: '^export CUDA_MPS_LOG_DIRECTORY=', line: 'export CUDA_MPS_LOG_DIRECTORY=/tmp/nvidia-log' }

- name: apply config
  become: True
  shell: source /etc/profile

