---

- name: Ensure that correct variable is exported in /etc/profile.d/cc-ssh-strong-rng.csh
  lineinfile:
    path: /etc/profile.d/cc-ssh-strong-rng.csh
    regexp: ^[\s]*setenv[\s]+SSH_USE_STRONG_RNG.*$
    line: setenv SSH_USE_STRONG_RNG 32
    state: present
    create: true
  tags:
  - configure_strategy
  - low_complexity
  - low_disruption
  - medium_severity
  - no_reboot_needed
  - ssh_client_use_strong_rng_csh

- name: Ensure that the configuration is not overridden in /etc/profile
  lineinfile:
    path: /etc/profile
    regexp: ^[\s]*setenv[\s]+SSH_USE_STRONG_RNG.*$
    state: absent
  tags:
  - configure_strategy
  - low_complexity
  - low_disruption
  - medium_severity
  - no_reboot_needed
  - ssh_client_use_strong_rng_csh
