---

- name: Set sshd Config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0600'

- name: Restart sshd
  become: True
  systemd:
    state: restarted
    name: sshd
