---

- name: Gather the package facts
  package_facts:
    manager: auto
  tags:
  - configure_strategy
  - low_complexity
  - low_disruption
  - medium_severity
  - no_reboot_needed
  - ssh_client_use_strong_rng_sh

- name: Ensure that correct variable is exported in /etc/profile.d/cc-ssh-strong-rng.sh
  lineinfile:
    path: /etc/profile.d/cc-ssh-strong-rng.sh
    regexp: ^[\s]*export[\s]+SSH_USE_STRONG_RNG=.*$
    line: export SSH_USE_STRONG_RNG=32
    state: present
    create: true
  when: '"kernel" in ansible_facts.packages'
  tags:
  - configure_strategy
  - low_complexity
  - low_disruption
  - medium_severity
  - no_reboot_needed
  - ssh_client_use_strong_rng_sh

- name: Ensure that the configuration is not overridden in /etc/profile
  lineinfile:
    path: /etc/profile
    regexp: ^[\s]*export[\s]+SSH_USE_STRONG_RNG=.*$
    state: absent
  when: '"kernel" in ansible_facts.packages'
  tags:
  - configure_strategy
  - low_complexity
  - low_disruption
  - medium_severity
  - no_reboot_needed
  - ssh_client_use_strong_rng_sh
