-- 방송서버 연동 기능
ALTER TABLE DMETA_ARTEVA.T_ARTEVA_BROADCAST_HIST ADD MESSAGE_SEQ int null comment '메시지 시퀀스' after EVENT_ID;
create index IDX_ARTEVA_BROADCAST_HIST_MESSAGE_IDX ON T_ARTEVA_BROADCAST_HIST (MESSAGE_SEQ);
ALTER TABLE DMETA_ARTEVA.T_ARTEVA_BROADCAST_HIST MODIFY EVENT_ID varchar(64) not null comment '이벤트 아이디';
ALTER TABLE DMETA_ARTEVA.T_ARTEVA_BROADCAST_HIST MODIFY RESULT char default 'T' not null comment '방송 성공여부 A:Ack, N:Nack, F:Fail, U:unknown, E:checksum error, T:Timeout';
ALTER TABLE DMETA_ARTEVA.T_ARTEVA_BROADCAST_HIST MODIFY BROADCAST_ID varchar(32) not null comment '방송내용 ID (EXT_BROADCAST_ID)';
ALTER TABLE DMETA_ARTEVA.T_ARTEVA_BROADCAST_HIST ADD AREA_CODE varchar(15) null after BROADCAST_TEXT;

-- 엘리베이터 연동 기능
ALTER TABLE DMETA_ARTEVA.T_ARTEVA_EXTERN_INFO ADD REQUEST_URL varchar(128) null comment 'URL for REST';
ALTER TABLE DMETA_ARTEVA.T_ARTEVA_EXTERN_INFO ADD LAST_ACCESS_TIME datetime null comment '마지막 호출 시';
ALTER TABLE DMETA_ARTEVA.T_ARTEVA_CAMERA_EVENT_CONF ADD ELEVATER_ID int null comment 'id for call elevator';
ALTER TABLE DMETA_ARTEVA.T_ARTEVA_CAMERA_EVENT_CONF_ARCHIVE ADD ELEVATER_ID int null comment 'id for call elevator' after EXPIRE_DURATION;

-- 상세코드 추가
-- 영상 감시, AI설정대분류, EVENT, EVENT, 이벤트 방송/엘리베이터 호출 설정
-- 영상 감시, AI설정중분류, ELEVATOR, ELEVATOR
-- 영상 감시, 연동시스템, EL, 엘리베이터
INSERT INTO LETTCCMMNDETAILCODE ( CODE_ID , CODE , CODE_NM , CODE_DC , USE_AT , FRST_REGIST_PNTTM , FRST_REGISTER_ID , LAST_UPDT_PNTTM , LAST_UPDUSR_ID ) VALUES ('AIPMC', 'EVENT', 'EVENT', '이벤트 방송/엘리베이터 호출 설정', 'Y', now(), '', now(), '');
INSERT INTO LETTCCMMNDETAILCODE ( CODE_ID , CODE , CODE_NM , CODE_DC , USE_AT , FRST_REGIST_PNTTM , FRST_REGISTER_ID , LAST_UPDT_PNTTM , LAST_UPDUSR_ID ) VALUES ('AIPNC', 'ELEVATOR', 'ELEVATOR', '엘리베이터 호출 설정', 'Y', now(), '', now(), '');
INSERT INTO LETTCCMMNDETAILCODE ( CODE_ID , CODE , CODE_NM , CODE_DC , USE_AT , FRST_REGIST_PNTTM , FRST_REGISTER_ID , LAST_UPDT_PNTTM , LAST_UPDUSR_ID ) VALUES('EXTSYS', 'EL', '엘리베이터', '엘리베이터 연동 제어기', 'Y', now(), '', now(), '');


-- 프로비저닝 관리 추가
INSERT INTO DMETA_ARTEVA.T_ARTEVA_PROVISIONING(CONFIG_NAME, CONFIG_VALUE, MAJ_CATEGORY, MIN_CATEGORY, OPTIONS, MEMO, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER, READONLY) VALUES ('ELEVATOR_INDEX', 0, 'EVENT', 'ELEVATOR', 'D', null, now(), now(), 'admin', 'admin', 'F');
INSERT INTO DMETA_ARTEVA.T_ARTEVA_PROVISIONING(CONFIG_NAME, CONFIG_VALUE, MAJ_CATEGORY, MIN_CATEGORY, OPTIONS, MEMO, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER, READONLY) VALUES ('ELEVATOR_ON_OFF_INTERVAL', 500, 'EVENT', 'ELEVATOR', 'D', '엘리베이터 ON/OFF 버튼 인터벌 설정', now(), now(), 'admin', 'admin', 'F');
INSERT INTO DMETA_ARTEVA.T_ARTEVA_PROVISIONING(CONFIG_NAME, CONFIG_VALUE, MAJ_CATEGORY, MIN_CATEGORY, OPTIONS, MEMO, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER, READONLY) VALUES ('ELEVATOR_REUSE_INTERVAL', 30, 'EVENT', 'ELEVATOR', 'D', '엘리베이터 호출 재시도 인터벌', now(), now(), 'admin', 'admin', 'F');
INSERT INTO DMETA_ARTEVA.T_ARTEVA_PROVISIONING(CONFIG_NAME, CONFIG_VALUE, MAJ_CATEGORY, MIN_CATEGORY, OPTIONS, MEMO, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER, READONLY) VALUES ('ELEVATOR_SPEAKER_INDEX', 1, 'EVENT', 'ELEVATOR', 'D', null, now(), now(), 'admin', 'admin', 'F');
