-- 방송서버 연동 기능
ALTER TABLE DMETA_ARTEVA.T_ARTEVA_BROADCAST_HIST DROP MESSAGE_SEQ;
-- DROP INDEX IDX_ARTEVA_BROADCAST_HIST_MESSAGE_IDX ON DMETA_ARTEVA.T_ARTEVA_BROADCAST_HIST;
ALTER TABLE DMETA_ARTEVA.T_ARTEVA_BROADCAST_HIST MODIFY EVENT_ID int(11) not null comment '이벤트 아이디';
ALTER TABLE DMETA_ARTEVA.T_ARTEVA_BROADCAST_HIST MODIFY RESULT char default 'T' not null comment '방송 성공여부 T/S/F';
ALTER TABLE DMETA_ARTEVA.T_ARTEVA_BROADCAST_HIST MODIFY BROADCAST_ID varchar(32) not null comment '방송내용 ID';
ALTER TABLE DMETA_ARTEVA.T_ARTEVA_BROADCAST_HIST DROP AREA_CODE;

-- 엘리베이터 연동 기능
ALTER TABLE DMETA_ARTEVA.T_ARTEVA_EXTERN_INFO DROP REQUEST_URL;
ALTER TABLE DMETA_ARTEVA.T_ARTEVA_EXTERN_INFO DROP LAST_ACCESS_TIME;
ALTER TABLE DMETA_ARTEVA.T_ARTEVA_CAMERA_EVENT_CONF DROP ELEVATER_ID;
ALTER TABLE DMETA_ARTEVA.T_ARTEVA_CAMERA_EVENT_CONF_ARCHIVE DROP ELEVATER_ID;

-- 상세코드 추가
-- 영상 감시, AI설정대분류, EVENT, EVENT, 이벤트 방송/엘리베이터 호출 설정
-- 영상 감시, AI설정중분류, ELEVATOR, ELEVATOR
-- 영상 감시, 연동시스템, EL, 엘리베이터
DELETE FROM LETTCCMMNDETAILCODE where CODE = 'EVENT';
DELETE FROM LETTCCMMNDETAILCODE where CODE = 'ELEVATOR';
DELETE FROM LETTCCMMNDETAILCODE where CODE = 'EL';

-- 프로비저닝 관리 추가
DELETE FROM DMETA_ARTEVA.T_ARTEVA_PROVISIONING WHERE CONFIG_NAME = 'ELEVATOR_INDEX';
DELETE FROM DMETA_ARTEVA.T_ARTEVA_PROVISIONING WHERE CONFIG_NAME = 'ELEVATOR_ON_OFF_INTERVAL';
DELETE FROM DMETA_ARTEVA.T_ARTEVA_PROVISIONING WHERE CONFIG_NAME = 'ELEVATOR_REUSE_INTERVAL';
DELETE FROM DMETA_ARTEVA.T_ARTEVA_PROVISIONING WHERE CONFIG_NAME = 'ELEVATOR_SPEAKER_INDEX';
