---

- name: EMS NE IP Select
  become: True
  become_user: "{{ username }}"
  become_flags: "-i"
  shell: python {{ script_dir }}/{{ my_script }} ne_id_name
  register: result

- name: Generate NE update sql
  template:
    src: cmysql-insert-ne-filter.sql.j2
    dest: "{{ tmp_dir }}/mysql_insert_ne_filter.sql"

- name: EMS filter IP Update
  mysql_db:
    name: nemsdb
    state: import
    login_user: nems
    login_password: nems
    target: "{{ tmp_dir }}/mysql_insert_ne_filter.sql"
