---

- name: mkdir keystore directory
  become: True
  file:
    path: "{{ clayhome }}/common/nems/keystore"
    group: "{{ username }}"
    owner: "{{ groupname }}"
    state: directory
    mode: '0755'

- name: get certfile
  become: True
  become_user: "{{ username }}"
  become_flags: "-i"
  shell: nconfigure get nems service service.https.keystore
  register: certfile

- name: get certpasswd
  become: True
  become_user: "{{ username }}"
  become_flags: "-i"
  shell: nconfigure get nems service service.https.keystore.password
  register: certpass

- name: check keystore file
  become: True
  stat:
    path: "{{ item }}"
  with_items:
    - "{{ certfile.stdout }}"
  register: check_file

- name: Copy certfile 
  fetch:
    src: "{{ certfile.stdout }}"
    dest: "../roles/config-ems/files/{{ ansible_host }}/"
    flat: yes
  with_items: "{{ check_file.results }}"
  when: item.stat.exists

- name: ssl cert import 
  become: True
  shell: |
    /usr/bin/keytool -genkey -alias server -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore {{ clayhome }}/common/nems/keystore/keystore.p12 -validity 36500 -storepass changeit -dname "CN=nable, OU=nable, O=nable, L=nable, S=nable, C=KR"
  register: result
  with_items: "{{ check_file.results }}"
  when: not item.stat.exists
    
- name: EMS nems Config setup
  become: True
  become_user: "{{ username }}"
  become_flags: "-i"
  shell: |
    nconfigure set nems service service.https.keystore.password changeit
    nconfigure set nems service service.https.keystore.alias server
    nconfigure set nems service service.https.keystore {{ clayhome }}/common/nems/keystore/keystore.p12
  with_items: "{{ check_file.results }}"
  when: not item.stat.exists

#- name: restart nems
#  become: True
#  become_user: "{{ username }}"
#  become_flags: "-i"
#  shell: nohup nrestart nems
