---

- name: Check the config 
  uri:
    url: http://10.10.0.211:8800/get.xml?id=vrrp&section=VRRP
    method: GET
    return_content: yes
  register: cnf

- name: display config
  debug:
    msg: "{{ item | replace('\r', '') }}"
  with_items:
    - "{{ cnf.content.split('\n') }}"

- name: save content 
  connection: local
  copy:
   content: "{{ cnf.content }}" 
   dest: "../file/nems_service.txt"
    
