---

- name: copy create template script
  become: True
  copy:
    src: "../script/{{ item }}"
    dest: "{{ clayhome }}/script"
    owner: "{{ username }}"
    group: "{{ groupname }}"
    mode: '0755'
  with_items:
    - parser_cliconf.py

- name: delete exist file
  become: True
  file:
    path: "{{ tmp_dir }}/config-{{ NE_Group }}.j2"
    state: absent

- name: create template files
  vars:
    pname: ""
  become: True
  become_user: "{{ username }}"
  become_flags: "-i"
  shell: "{{ clayhome }}/script/parser_cliconf.py get package {{ pname }} > {{ tmp_dir }}/config-{{ NE_Group }}.j2"

- name: get template file
  become: True
  fetch:
    src: "{{ tmp_dir }}/config-{{ NE_Group }}.j2"
    dest: "../roles/config-ems/templates/"
    flat: yes
  run_once: yes

- name: Config ems
  connection: local
  template:
    src: "config-{{ NE_Group }}.j2"
    dest: "../roles/config-ems/templates/config-{{ NE_Group |lower }}.j2"
