---

  ClientAliveInterval: !!str 300
  ClientAliveCountMax: !!str 0

  var_ssh_client_rekey_limit_size: "1G"
  var_ssh_client_rekey_limit_time: "1h"

  var_accounts_user_umask: !!str 022
  var_accounts_max_concurrent_login_sessions: !!str 10

  sysctl_net_ipv4_conf_default_rp_filter_value: !!str 1
  sysctl_net_ipv4_icmp_echo_ignore_broadcasts_value: !!str 1
  sysctl_net_ipv6_conf_default_accept_redirects_value: !!str 0
  sysctl_net_ipv4_icmp_ignore_bogus_error_responses_value: !!str 1
  sysctl_net_ipv6_conf_all_accept_redirects_value: !!str 0
  sysctl_net_ipv4_conf_default_accept_redirects_value: !!str 0
  sysctl_net_ipv4_conf_default_log_martians_value: !!str 1
  sysctl_net_ipv4_conf_all_log_martians_value: !!str 1
  sysctl_net_ipv6_conf_default_accept_ra_value: !!str 0
  sysctl_net_ipv6_conf_all_accept_ra_value: !!str 0
  sysctl_net_ipv4_conf_default_secure_redirects_value: !!str 0
  sysctl_net_ipv4_tcp_syncookies_value: !!str 1
  sysctl_net_ipv4_conf_all_secure_redirects_value: !!str 0
  sysctl_net_ipv4_conf_all_accept_redirects_value: !!str 0
  sysctl_net_ipv4_conf_default_accept_source_route_value: !!str 0
  sysctl_net_ipv6_conf_default_accept_source_route_value: !!str 0
  sysctl_net_ipv6_conf_all_accept_source_route_value: !!str 0

  var_slub_debug_options: !!str P

  var_password_pam_unix_remember: !!str 5
  var_password_pam_maxclassrepeat: !!str 4
  var_password_pam_minclass: !!str 4
  var_password_pam_difok: !!str 4
  var_password_pam_dcredit: !!str -1
  var_password_pam_minlen: !!str 12
  var_password_pam_lcredit: !!str -1
  var_password_pam_ocredit: !!str -1
  var_password_pam_ucredit: !!str -1
  var_password_pam_maxrepeat: !!str 3

  var_system_crypto_policy: !!str FIPS:OSPP

  sshd_approved_ciphers: !!str aes256-ctr,aes192-ctr,aes128-ctr,aes256-gcm@openssh.com,aes128-gcm@openssh.com
  sshd_approved_macs: !!str hmac-sha2-512,hmac-sha2-256,hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com
