---

- name: update root passwd
  become: True
  shell: |
    mariadb -u root mysql -e 'alter user root@localhost identified via mysql_native_password using password("dmeta!@34");'
    #mariadb -u root mysql -e 'flush privileges;'
