---

#- name: Check backup file
#  stat:
#    path: "{{ apps_dir }}/arteva/cert/{{ item }}"
#  with_items:
#    - 'cacert.crt'
#  no_log: True
#  register: check_file

- name: Backup old certificate 
  become: True
  copy:
    src: "{{ apps_dir }}/arteva/cert/{{ item }}"
    dest: "{{ apps_dir }}/arteva/cert/{{ item }}.orig"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_user }}"
    remote_src: yes
  with_items:
    - 'cacert.crt'
    - 'client.crt'
    - 'client.key'

- name: upload src rpm files
  become: True
  copy:
    src: "{{ def_dir }}/{{ item }}"
    dest: "{{ apps_dir }}/arteva/cert"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_user }}"
  with_items:
    - 'cacert.crt'
    - 'client.crt'
    - 'client.key'
