---

- name: upload sql files
  become: True
  copy:
    src: "{{ def_dir }}/{{ item }}"
    dest: "{{ apps_dir }}/{{ ai_dir }}/{{ item }}"
  with_items:
    - "insert_model.sql"

- name: alter table
  become: True
  mysql_db:
    name: "{{ database }}"
    state: import
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    target: "{{ apps_dir }}/{{ ai_dir }}/insert_model.sql"
