---

- name: upload https server.xml
  become: True
  template:
    src: server-http.xml.j2
    dest: "{{ apps_dir }}/tomcat/conf/{{ item }}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_user }}"
  with_items:
    - "server.xml"

- name: restarted tomcat 
  become: True
  systemd:
    name: tomcat
    state: restarted
    enabled: yes
