---

- name: create pose_logic directory
  become: True
  file:
    path: /apps/arteva/ai_engine/ai_process/pose_logic
    state: directory
    owner: tomcat
    group: tomcat

- name: backup ai file
  become: True
  copy:
    src: "{{ apps_dir }}/PKG/{{ pkg_dir }}/ai/file/{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_user }}"
    remote_src: yes
  with_items:
    - { src: 'run_arteva.sh', dest: '/apps/arteva/ai_engine/run_arteva.sh' }
    - { src: 'worker_manager.py', dest: '/apps/arteva/ai_engine/worker_manager.py' }
    - { src: 'arteva.py', dest: '/apps/arteva/ai_engine/ai_process/arteva.py' }
    - { src: 'camera_thread.py', dest: '/apps/arteva/ai_engine/ai_process/camera_thread.py' }
    - { src: 'central_inference_worker.py', dest: '/apps/arteva/ai_engine/ai_process/central_inference_worker.py' }
    - { src: 'event_manager.py', dest: '/apps/arteva/ai_engine/ai_process/event_manager.py' }
    - { src: 'yolo_v8_medium_x32.engine', dest: '/apps/arteva/ai_engine/ai_process/model/weights/v4/detect/yolo_v8_medium_x32.engine' }
    - { src: 'lwdetr_medium_fp16_msgs.onnx', dest: '/apps/arteva/ai_engine/ai_process/model/weights/v4/detect/lwdetr_medium_fp16_msgs.onnx' }
    - { src: '__init__.py', dest: '/apps/arteva/ai_engine/ai_process/pose_logic/__init__.py' }
    - { src: 'falldown_detection.py', dest: '/apps/arteva/ai_engine/ai_process/pose_logic/falldown_detection.py' }
    - { src: 'violence_detection.py', dest: '/apps/arteva/ai_engine/ai_process/pose_logic/violence_detection.py' }
    - { src: 'group_violence_detection.py', dest: '/apps/arteva/ai_engine/ai_process/pose_logic/group_violence_detection.py' }
    - { src: 'shadow.py', dest: '/apps/arteva/ai_engine/ai_process/pose_logic/shadow.py' }
    - { src: 'obj_utils.py', dest: '/apps/arteva/ai_engine/common/utils/obj_utils.py' }
    - { src: 'app.py', dest: '/apps/arteva/ai_engine/process_manager/app.py' }
    - { src: 'process_manager_master.py', dest: '/apps/arteva/ai_engine/process_manager/service/process_manager_master.py' }
    - { src: 'shared_memory.py', dest: '/apps/arteva/ai_engine/process_manager/service/shared_memory.py' }
    - { src: 'packet_pipeline.py', dest: '/apps/arteva/ai_engine/rtsp_process/packet_pipeline.py' }
    - { src: 'client.py', dest: '/apps/arteva/ai_engine/rtsp_process/infurastructure/rtsp/client.py' }
    - { src: 'rtsp_thread.py', dest: '/apps/arteva/ai_engine/rtsp_process/service/rtsp_thread.py' }
    - { src: 'frame_store.py', dest: '/apps/arteva/ai_engine/rtsp_process/tool/frame_store.py' }
    - { src: 'gpu_stream_decoder.py', dest: '/apps/arteva/ai_engine/rtsp_process/tool/gpu_stream_decoder.py' }
    - { src: 'single_buffer.py', dest: '/apps/arteva/ai_engine/rtsp_process/tool/single_buffer.py' }
