---

- name: install arteva service
  gather_facts: True
  vars:
    hostname: "arteva1"
    host: arteva
  hosts: "{{ host }}"
  become: True 

  roles:
    - role: install-service
    - role: install-ai-engine
