---

- name: Put contents into /etc/audit/rules.d/11-loginuid.rules according to policy
  template:
    src: 11-loginuid.rules.j2
    dest: /etc/audit/rules.d/11-loginuid.rules
    owner: root
    group: root
    mode: '0640'
  tags:
  - NIST-800-53-AU-2(a)
  - audit_immutable_login_uids
  - low_complexity
  - low_disruption
  - medium_severity
  - no_reboot_needed
  - restrict_strategy

#- name: Remove any permissions from other group
#  file:
#    path: /etc/audit/rules.d/11-loginuid.rules
#    mode: o-rwx
#  tags:
#  - NIST-800-53-AU-2(a)
#  - audit_immutable_login_uids
#  - low_complexity
#  - low_disruption
#  - medium_severity
#  - no_reboot_needed
#  - restrict_strategy
