---

- name: Put contents into /etc/audit/rules.d/30-ospp-v42-3-access-success.rules according to policy
  template:
    src: 30-ospp-v42-3-access-success.rules.j2
    dest: /etc/audit/rules.d/30-ospp-v42-3-access-success.rules
    owner: root
    group: root
    mode: '0640'

#- name: Remove any permissions from other group
#  file:
#    path: /etc/audit/rules.d/30-ospp-v42-3-access-success.rules
#    mode: o-rwx
#  tags:
#  - NIST-800-53-AU-2(a)
#  - audit_access_success
#  - low_complexity
#  - low_disruption
#  - medium_severity
#  - no_reboot_needed
#  - restrict_strategy
