---

- name: Put contents into /etc/audit/rules.d/30-ospp-v42-6-owner-change-failed.rules according to policy
  template:
    src: 30-ospp-v42-6-owner-change-failed.rules.j2
    dest: /etc/audit/rules.d/30-ospp-v42-6-owner-change-failed.rules
    owner: root
    group: root
    mode: '0640'
  tags:
  - NIST-800-53-AU-2(a)
  - audit_owner_change_failed
  - low_complexity
  - low_disruption
  - medium_severity
  - no_reboot_needed
  - restrict_strategy

#- name: Remove any permissions from other group
#  file:
#    path: /etc/audit/rules.d/30-ospp-v42-6-owner-change-failed.rules
#    mode: o-rwx
#  tags:
#  - NIST-800-53-AU-2(a)
#  - audit_owner_change_failed
#  - low_complexity
#  - low_disruption
#  - medium_severity
#  - no_reboot_needed
#  - restrict_strategy
