---

- name: Require Authentication for Single User Mode - Require emergency user mode password
  community.general.ini_file:
    path: /etc/systemd/system/rescue.service.d/10-oscap.conf
    section: Service
    option: ExecStart
    value: -/usr/lib/systemd/systemd-sulogin-shell rescue
  tags:
  - DISA-STIG-RHEL-08-010151
  - NIST-800-171-3.1.1
  - NIST-800-171-3.4.5
  - NIST-800-53-AC-3
  - NIST-800-53-CM-6(a)
  - NIST-800-53-IA-2
  - low_complexity
  - low_disruption
  - medium_severity
  - no_reboot_needed
  - require_singleuser_auth
  - restrict_strategy
