---

- name: config sysctl 
  sysctl:
    name: "{{ item }}"
    value: 0
    sysctl_set: yes
    state: present
    reload: yes
  with_items:
    - net.ipv6.conf.all.dad_transmits
    - net.ipv6.conf.default.dad_transmits

